### ISSUE TITLE
Admin.py Category list_filter display issue, with Parler+MPTT

### ISSUE THREAD

**Issue by sunjoomoon** [django-parler/django-parler#146]
I have both Page and Category with MPTT + Parler, and with

```
class Page(MPTTModel, TranslatableModel):
    parent = models.ForeignKey('self', null=True, blank=True,related_name='children')       
    translations = TranslatedFields(
        title = models.CharField(_('Title'), max_length=255, unique=True),
...

class Category(TranslatableModel):     
    translations = TranslatedFields(
    title = models.CharField(_('Title'), max_length=250, help_text=_('Title Should Have Capitalized Words')),
...
```

And in admin.py I have below, the thing is 'category' is NOT shown as it is under translation, How can I display the category in the filter?
```
class ArticleAdmin(TranslatableAdmin, admin.ModelAdmin): 
...
    list_filter = ('is_published', 'category')    
...
```

**Comment by vdboor** [comment]
@sunjoomoon how is the category connected to the article? Could this be a Django model error instead of a parler issue?

**Comment by sunjoomoon** [comment]
Hi, sorry for the late one. Somehow if more than two categories, then they ARE shown. If just one category, then category is NOT shown. That makes sense somehow though.
