### ISSUE TITLE
ValidationError using en-us locale

### ISSUE THREAD

**Issue by facciocose** [django-parler/django-parler#147]
I have a Tag model like this one:

    class Tag(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=255),
    )

    def __str__(self):
        return self.name

and my settings.py are configured like this:

    LANGUAGE_CODE = 'en-us'
    TIME_ZONE = 'UTC'
    USE_I18N = True
    USE_L10N = True
    USE_TZ = True

    # parler config
    PARLER_LANGUAGES = {
        None: (
            {'code': 'en-us'},
            {'code': 'it'},
        ),
    }

When I try to insert a new item in my model from the admin interface I get the following error: `'TagForm' has no field named 'language_code'.`.

Inspecting the stack seems that the problem is a validator.

    error_dict	{'language_code': [ValidationError([u"Value u'en-us' is not a valid choice."])]}
    self	<TagForm bound=True, valid=True, fields=(name)>
    messages	[ValidationError([u"Value u'en-us' is not a valid choice."])]
    field	'language_code'
    errors	ValidationError({'language_code': [u"Value u'en-us' is not a valid choice."]})
    opts	<django.forms.models.ModelFormOptions object at 0x1071f3810>

If I use **en** instead of **en-us** as language everything works as expected.

I think it's a problem with the dash in the language name.

**Comment by vdboor** [comment]
I think this can be worked around by adding a `LANGUAGES` setting to your project. The "language_code" column uses `choices=settings.LANGUAGES`.

For example:

```
LANGUAGES = (
    ('en', _('English')),
    ('en-us', _('US English')),
    ('it', _('Italian')),
)
```

Likely we need to update the docs here, improve the validation errors, or exclude `language_code` from the validation.

**Comment by facciocose** [comment]
Thanks!

Btw in settings is not needed to use **_**

In the end I used

    LANGUAGES = (
        ('en-us', 'English'),
        ('it', 'Italian'),
    )
