### ISSUE TITLE
Language restrictions are too broad

### ISSUE THREAD

**Issue by mdentremont** [django-parler/django-parler#156]
Version 1.6.5 adds validation which only allows usage of languages in the `LANGUAGES` setting.

This restriction is blocking sublanguage codes, such as 'en-us'.

From the docs (https://docs.djangoproject.com/en/1.10/topics/i18n/translation/):

> Only languages listed in the LANGUAGES setting can be selected. If you want to restrict the language selection to a subset of provided languages (because your application doesn’t provide all those languages), set LANGUAGES to a list of languages. For example:
> 
> ``` python
> LANGUAGES = [
>   ('de', _('German')),
>   ('en', _('English')),
> ]
> ```
> 
> This example restricts languages that are available for automatic selection to German and English (and any sublanguage, like de-ch or en-us).

The last portion indicates that adding `en` to `LANGUAGES` also enable sublanguages such as `en-us`.

This is going to affect many users of this library, as `en-us` is Django's default language code.

**Comment by orf** [comment]
This is very annoying, I'm just getting started with the library and this immediately hits you in the face.

**Comment by vdboor** [comment]
@yakky, can we look into this?
