### ISSUE TITLE
Django-parler together with django-extra-views (CBV)

### ISSUE THREAD

**Issue by hetsch** [django-parler/django-parler#166]
I'm trying to use both libraries `django-parler` and `django-extra-views` together in a project. What I have right now, is a simple multilingual event form that also contains some inline forms, in my case different dates. While I'm successful at creating an event entry with it's related date entries, I fail if I try to update the event in a particular language, because all the related (inline) date entries do not use the language of the event, but instead use the fallback language if they are saved. I suspect that the in my case, `TranslatableModelFormMixin` does not inherit the current language of the event (chosen via the `?language` attribute) to the multiple dates objects. 

This seems to be problematic in a situation, if an admin user want's to add a new language translation to an event, but the related dates are always loaded and saved in the fallback language. The language fallback is really useful for frontend pages to show show alternative content, but while editing an object in an admin form the behavior should be that if no translation is found, don't fallback to give the user a chance to create translation entries in a new language. Is it possible to disable the language fallback behavior on a per request basis if one want's to build a admin form to provide the user the ability to change the language?

It might be that I'm totally off right now and I have no idea if the below code and my understanding is terribly wrong, or if both packages are indeed incompatible.

My simplified code of `views.py` is:

```
from django.views.generic import DetailView

from parler.forms import TranslatableModelForm
from parler.views import TranslatableModelFormMixin, LanguageChoiceMixin

from extra_views import InlineFormSet, CreateWithInlinesView, UpdateWithInlinesView

from .models import Event, Date


class EventForm(TranslatableModelForm):
    class Meta:
        model = Event
        fields = '__all__'


class DateForm(TranslatableModelForm):
    class Meta:
        model = Date
        fields = '__all__'


class DateInlineCreateFormSet(InlineFormSet):
    model = Date
    form_class = DateForm
    fields = '__all__'
    extra = 3
    can_delete = False


class DateInlineUpdateFormSet(InlineFormSet):
    model = Date
    form_class = DateForm
    fields = '__all__'
    extra = 1
    can_delete = True


class EventDetailView(LanguageChoiceMixin, DetailView):
    model = Event


class EventCreateView(TranslatableModelFormMixin, CreateWithInlinesView):
    model = Event
    form_class = EventForm
    inlines = [DateInlineCreateFormSet,]

    def get_success_url(self):
        return self.object.get_absolute_url()


class EventUpdateView(TranslatableModelFormMixin, UpdateWithInlinesView):
    model = Event
    form_class = EventForm
    inlines = [DateInlineUpdateFormSet,]

    def get_success_url(self):
        return self.object.get_absolute_url()
```

My `models.py`:

```
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse

from parler.models import TranslatableModel, TranslatedFields


class Event(TranslatableModel):

    translations = TranslatedFields(
        title = models.CharField(_("Title"), max_length=255)
    )

    def get_absolute_url(self):
        return reverse('events:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Date(TranslatableModel):

    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    translations = TranslatedFields(
        title = models.CharField(_("Title"), max_length=255)
    )

    def __str__(self):
        return self.title
```

My `ulrs.py`:

```
from django.conf.urls import url

from .views import EventCreateView, EventDetailView, EventUpdateView

urlpatterns = [
    url(r'^create/$', EventCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', EventDetailView.as_view(), name='detail'),
    url(r'^edit/(?P<pk>\d+)/$', EventUpdateView.as_view(), name='update'),
]
```

My views `event_form.html` and `event_detail.html`:

```
<!-- event_form.html -->
{% extends "base.html" %}

{% load i18n %}

{% block content %}
<form method="post" action="{{ request.get_full_path }}">
    {% csrf_token %}
    {{ form }}<br>
    <h3>Dates</h3>
    {% for inline in inlines %}
        {{ inline }}<br>
    {% endfor %}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

<!-- event_detail.html -->
{% extends "base.html" %}

{% load i18n %}

{% block content %}
{{ object }}<br>
<h3>Dates</h3>
{% for date in object.date_set.all %}
    {{ date }}<br>
{% endfor %}
{% endblock %}
```

**Comment by hetsch** [comment]
I think this is more a problem of setting the same language on ForeignKey fields/relationships than in the master object. If I explicitly force a language in the template it works. But this seems to a little bit hackish to me ...

    {% extends "base.html" %}

    {% load i18n parler_tags %}

    {% block content %}
    {{ object }}<br>
    <h3>Dates</h3>
    {% for date in object.date_set.all %}
        {% objectlanguage date object.get_current_language %}
            {{ date }}<br>
        {% endobjectlanguage %}
    {% endfor %}
    {% endblock %}
</form>

**Comment by vdboor** [comment]
You're right that setting the language is a bit hackish. While the `TranslatableModelFormMixin` makes sure the form is initialized with the proper language, it's your responsability to make sure the `extra_views` also receive the language paramerter, and create the objects accordingly.

Setting the language works, only because models read Django's language when none is given via the `_current_language` kwarg.

**Comment by hetsch** [comment]
Excuse me for coming back that late and thank you for having a look into my problem. I think I've understood it now how it might work.
