### ISSUE TITLE
Caching is not multi-project safe

### ISSUE THREAD

**Issue by mkoistinen** [django-parler/django-parler#167]
When deploying multiple projects on the same server, using the same cache backend, translations get crossed. One project may retrieve another projects translations for objects with similar IDs. This is particularly likely if both projects use a common translated package in their projects as the cache key will end up identical.

Offending line is here: https://github.com/django-parler/django-parler/blob/master/parler/cache.py#L62

This should incorporate the project's `CACHE_MIDDLEWARE_PREFIX` in the key, to keep the cache independent for each project. Or use a similar strategy.

Work-around in the short term (for anyone arriving here via search) is to use: `PARLER_ENABLE_CACHING = False` in your settings.

**Comment by vdboor** [comment]
@mkoistinen, if you add a `KEY_PREFIX` to your `CACHES` seting, I'd expect this to work as well. Can you confirm this?

**Comment by mkoistinen** [comment]
I think you're right. Sorry. Closing.
