### ISSUE TITLE
Tox does work anymore

### ISSUE THREAD

**Issue by yakky** [django-parler/django-parler#170]
``python setup.py sdist`` requires django to run, which does not exists when running tox

**Comment by vdboor** [comment]
A it seems this changed in recent tox versions.
I was still using tox 2.3.1 (installed globally) which creates the sdist inside the env.

The `sdist` trick was used to avoid adding compiled files (`*.mo`) in the git repository, but have them available on building the package. We'll have to find a better way to handle this.

**Comment by yakky** [comment]
Not a top priority, anyway. I just reported this as I discovered

**Comment by vstoykov** [comment]
If there are globally installed django it should work (no mater which version).

**Comment by vdboor** [comment]
thanks @vstoykov, I'll leave it like this for now.
