### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by techdragon** [django-parler/django-parler#171]
It would be good to get a new release containing the fixes from solving #90 since at the moment using parter is more likely to have conflicts with management commands than it needs to be since we have the fixes written.

**Comment by yakky** [comment]
I'm :+1: 
@vdboor ?

**Comment by vdboor** [comment]
@yakky, @techdragon django-parler 1.7 is out with the fix included!
Sorry for the lond delay, I didn't see this notification message.
