### ISSUE TITLE
Django 1.10.3 with Python 3.4.3 compatibility

### ISSUE THREAD

**Issue by Artem19861910** [django-parler/django-parler#175]
Hi community!

Today I had pity experience in using django-parler, v.1.7, installed via pip.

When I tried shell command `./manage.py makemigrations shop --name "add_translation_model"` terminal sends me in a far-away-land and told my back:

`TypeError: The model 'Category' already has a field named 'name'`

I checked all including commas and apostrophes. And suspicions fell on compatibility with 1.10.3... Am I right?

**Comment by yakky** [comment]
@Artem19861910 could you share the code of your model?

**Comment by Artem19861910** [comment]
Here code of my model. Some fields I commented because they do not bear any sense for now.
`from django.db import models
from django.core.urlresolvers import reverse

##from parler.models import TranslatableModel, TranslatedFields
## parler is not compatible with dajngo 1.10


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

##    translations = TranslatedFields(
##        name = models.CharField(max_length=200, db_index=True),
##        slug = models.SlugField(max_length=200, db_index=True, unique=True),
##    )

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)    
    description = models.TextField(blank=True)
##    translations = TranslatedFields(
##        name = models.CharField(max_length=200, db_index=True),
##        slug = models.SlugField(max_length=200, db_index=True),    
##        description = models.TextField(blank=True),
##    )
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    category = models.ForeignKey(Category, related_name='products')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])
`

**Comment by vdboor** [comment]
@Artem19861910 you can't have a `name` field on the model, and in the `TranslatedFields` block. Either you have a standard field, or a translated field, but not both
