### ISSUE TITLE
Admin list view question.

### ISSUE THREAD

**Issue by dg1980** [django-parler/django-parler#182]
Dear @vdboor 

I have a question about about admin list view. 

I configured Parler accordingly to the documentation and I use Django 1.10. Everything works nice, but I noticed one "issue". 

Target and translated objects appears together in the list view of the admin site. Is it proper behavior of the Parler (in the admin list view)?

**Comment by vdboor** [comment]
yes, you'll see the objects with the "fallback" language and translated language. You can however, choose to hide untranslated objects globally. This is a global setting, and the admin reflects that.
