### ISSUE TITLE
Query issue: .distinct() not working correctly with/due to Parler?

### ISSUE THREAD

**Issue by maltebeckmann** [django-parler/django-parler#183]
[Update: I just tried simplifying the presentation of the issue below]

I am experiencing an unexpected issue with querying for cities I have in a translatable City model. The City model has a non-translated field called country (see model below). Now, I wanted to get a list of countries with .distinct() but I am getting more than one than one of the same country in the returned list.

I have two queries:
Query 1) countries_count = City.objects.values('country').filter(translations__language_code="zh-hans").distinct().count()
Query 2) countries = City.objects.values('country').filter(translations__language_code="zh-hans").distinct()

RETURNS:
countries_count: (3)
countries:
{'country': 'DE'}
{'country': 'ES'}
{'country': 'CN'}
{'country': 'CN'}
{'country': 'CN'}
{'country': 'CN'}
{'country': 'CN'}
{'country': 'CN'}
{'country': 'CN'}
{'country': 'CN'}
{'country': 'CN'}
{'country': 'CN'}

So Query 1 works because it should be 3 countries. But Query 2 returns CN (China) 10 times. How can this be despite the .distinct()? Why is the count correct?

Even when I do run .count() on the above countries, I get 3: countries.count()

We believe this somehow has to be related to Django Parler because we can't see any other thing that could be interfering with this. Could this be the case?

Here is what the City model looks like and my CMS settings:

My CMS settings are:

CMS_LANGUAGES = {
    ## Customize this
    1: [
        {
            'public': True,
            'hide_untranslated': True,
            'code': 'en',
            'redirect_on_fallback': True,
            'fallbacks': ['en',],
            'name': 'English',
        },
        {
            'public': True,
            'hide_untranslated': True,
            'code': 'zh-hans',
            'redirect_on_fallback': True,
            'fallbacks': ['zh-hans',],
            'name': '中文',
        },
       ],
    'default': {
        'public': True,
        'redirect_on_fallback': True,
        'hide_untranslated': True,
        },
}

    class City(TranslatableModel):

    class Meta:
        app_label = 'cities'
        verbose_name = _('city')
        verbose_name_plural = _('cities')
        ordering = ['city_order',]

    translations = TranslatedFields(

        title = models.CharField(
            'name',
            blank=False,
            default='',
            help_text='Provide the name of the city.',
            max_length=255,
        )
    )

        COUNTRIES = (
        ('AT', _('Austria')),        
        ('BE', _('Belgium')),
        ('BG', _('Bulgaria')),
        ('CN', _('China')),
        ('HR', _('Croatia')),
        ('CY', _('Cyprus')),
        ('CZ', _('Czech Republic')),
        ('DK', _('Denmark')),
        ('EE', _('Estonia')),
        ('FI', _('Finland')),
        ('FR', _('France')),
        ('DE', _('Germany')),
        ('GB', _('Great Britain')),            
        ('GR', _('Greece')),
        ('HU', _('Hungary')),
        ('IS', _('Iceland')),
        ('IE', _('Ireland')),
        ('IT', _('Italy')),
        ('LV', _('Latvia')),
        ('LT', _('Lithuania')),
        ('LU', _('Luxembourg')),
        ('MT', _('Malta')),
        ('NL', _('Netherlands')),
        ('NO', _('Norway')),
        ('PL', _('Poland')),
        ('PT', _('Portugal')),
        ('RS', _('Servia')),
        ('RO', _('Romania')),
        ('SK', _('Slovakia')),
        ('SI', _('Slovenia')),
        ('ES', _('Spain')),
        ('SE', _('Sweden')),
        ('CH', _('Switzerland')),
    )

    country = models.CharField(choices=COUNTRIES, max_length=2, null=True, blank=True)

**Comment by maltebeckmann** [comment]
Anyone?

**Comment by vstoykov** [comment]
Can you show the result of:
```
print(City.objects.values('country').filter(translations__language_code="zh-hans").distinct().query)
```

**Comment by maltebeckmann** [comment]
Hi @vstoykov thanks for getting back to me! Your question alone was enough to help us figure it out. So it was ordering related: "cities_city"."city_order".

Here is the output from the print statement:

SELECT DISTINCT "cities_city"."country", "cities_city"."city_order" FROM "cities_city" INNER JOIN "cities_city_translation" ON ("cities_city"."id" = "cities_city_translation"."master_id") WHERE "cities_city_translation"."language_code" = zh-hans ORDER BY "cities_city"."city_order" ASC

I solved this by adding a order_by():
all_countries = City.objects.values('country').filter(translations__language_code="zh-hans").order_by().distinct() 

Thanks for asking the right question!
