### ISSUE TITLE
Django 1.11 compatibility

### ISSUE THREAD

**Issue by BernhardPosselt** [django-parler/django-parler#185]
Hi @vdboor 

Seems that this package is not yet ready for 1.11, the CI build does not include 1.11 and I've got errors when I switch to the latest Django version (seems relevant things got removed?). Since 1.11 is an LTS and 1.10 support [will run out come December](https://www.djangoproject.com/weblog/2015/jun/25/roadmap/) it would be nice if it was ready :)

I know maintaing a lib is hard work, so what is your current plan? Do you need help?

Apart from that it would be a good idea to also run the CI build on the latest master (and put it on allowed failures).

**Comment by vdboor** [comment]
Hi @BernhardPosselt , getting help would be greatly appreciated! If you like, I can make you a co-maintainer. There are many other things on my plate, so it makes parler essentially a maintenance project for me.

From a quick look, the basic things seems to be running fine on Django 1.11. I do notice that the tests still break. I've enabled Django 1.10 and 1.11 in travis, and updated the `tox.ini` file for local testing.

**Comment by BernhardPosselt** [comment]
Any idea why the corner cases fail?

I'm personally heavily involved into other stuff (Nextcloud News app, store, picoFeed RSS lib) plus have a little kid and work so I can't contribute regularely if at all at times.

I'm however interested that the project is at least compatible with current Django versions :)

**Comment by BernhardPosselt** [comment]
BTW, even basic things like setting languages fails for me on 1.11

**Comment by vdboor** [comment]
I've just fixed the tests in 473903a6f88347b599f4c96c8990efbcbfd8d6b3
The only real bug was our `LanguageCodeDescriptor` that didn't allow iteration via  the model `Options._property_names`. All other bugs were caused by 2 tests that corrupted the Django 1.10/1.11 app registry cache. Skipping those tests made all other bugs disappear

**Comment by BernhardPosselt** [comment]
Awesome :) ty

**Comment by vdboor** [comment]
I've released 1.8 with the fixes, which also drops Django 1.5/1.6 and Python 2.6 support.
