### ISSUE TITLE
Preferred way to make django-parler fields sortable in admin

### ISSUE THREAD

**Issue by maltebeckmann** [django-parler/django-parler#187]
Found this thread from 2015. Is this still valid? Any other way to make django-parler fields sortable in admin?

https://stackoverflow.com/questions/29909036/preferred-way-to-make-django-parler-fields-sortable-in-admin

**Comment by vdboor** [comment]
Hi!

Parts of this topic are still valid. However, as of Django 1.8 you can use SQL expressions like `Coalesce` directly in the ORM. Thus, raw SQL is likely not needed anymore.

**Comment by maltebeckmann** [comment]
Thanks!
