### ISSUE TITLE
get_or_create() not working with Django 1.11+

### ISSUE THREAD

**Issue by jjkalucki** [django-parler/django-parler#189]
[fields.diff.txt](https://github.com/django-parler/django-parler/files/1090913/fields.diff.txt)
I still have issues with new Django and 1.8 parler release.
Temporary I fixed my problems with the following fix

**Comment by vdboor** [comment]
Thanks for letting me know!

I'm a bit surprised this issue still occurs, as my 1.11 site doesn't have any problems.
Could you post a traceback, or perhaps even a workable demo where things go wrong?

**Comment by jjkalucki** [comment]
Diederik van der Boor pisze:
    
    
      I'm a bit surprised this issue still occurs, as my 1.11 site
        doesn't have any problems.
        Could you post a traceback, or perhaps even a workable demo
        where things go wrong?
    
    
    Hi.
    
    I've found that parler fails on calling
    django.db.models.query.QuerySet get_or_create() and
    update_or_create() methods,
    because of changes in QuerySet._extract_model_params() method where
    model fields are verified.
    There is developer notice in line 527 of django query.py module:
        # It's okay to use a model's property if it has a setter.
    Otherwise field is considered invalid.
    I have no free time to create workable demo right now, but first
    time where I noticed this problem was shuup 
    I'll try to try prepare for you quick demo within this weekend.
    -- 
Regards,
Jacek Kałucki
