### ISSUE TITLE
using TranslatedFields in related lookups

### ISSUE THREAD

**Issue by ozgurakcali** [django-parler/django-parler#194]
I have a Country model, which has a translateable name field as follows:

    class Country(TranslatableModel):
        iso_code = models.CharField(max_length=5)
        phone_code = models.IntegerField()

        translations = TranslatedFields(
            name=models.CharField(max_length=80)
        )

I have another model which has a country field referencing a Country object. I want to be able to make related lookups with country name, anyway I can do a query like:

    MyModel.objects.filter(country__name='Austria')

**Comment by vdboor** [comment]
You can use the `.translated(name="Austria")` code, or filter on `.filter(translations__name="Austria")`. Note you may need `.distinct()` as the lookup on the translations table may return multiple results. The documentation also discusses this.
