### ISSUE TITLE
null=True for master ForeignKey

### ISSUE THREAD

**Issue by BenjiLee** [django-parler/django-parler#196]
https://github.com/django-parler/django-parler/blob/master/docs/advanced/manual-models.rst

```python
from django.db import models
from parler.models import TranslatableModel, TranslatedFieldsModel
from parler.fields import TranslatedField


class MyModel(TranslatableModel):
    title = TranslatedField()  # Optional, explicitly mention the field

    class Meta:
        verbose_name = _("MyModel")

    def __unicode__(self):
        return self.title


class MyModelTranslation(TranslatedFieldsModel):
    master = models.ForeignKey(MyModel, related_name='translations', null=True)
    title = models.CharField(_("Title"), max_length=200)

    class Meta:
        unique_together = ('language_code', 'master')
        verbose_name = _("MyModel translation")
```

It looks like in the documentation, when creating a TranslatedFieldsModel, `null=True` for the master ForeignKey.
When creating a TranslatedFieldsModel, is there any way for the `master` ForeignKey to have a `null` value?

**Comment by vdboor** [comment]
No it can't. However we've kept that notation there to keep the model definition identical to the one generated by `create_translations_model()`.
