### ISSUE TITLE
Hiding languages in LANGUAGE columns in admin list_display

### ISSUE THREAD

**Issue by sunjoomoon** [django-parler/django-parler#198]
Say, I had three languages - English, Korean and Chinese and now I just have just two - English and Korean, and set as such in settings.py as well.

The challenge is I still see 'Chinese' in languages column of admin list_display. Of course when I click the Chinese language, I get '`502 Bad Gateway`' error. Obvious that Chinese is NOT in settings.py. Yes, language tabs are all fine - they just show the languages defined in settings.py

It looks confusing and certainly clients will be tempted to click the language. How can I hide the languages not in settings.py?

**Comment by vdboor** [comment]
Do you have `PARLER_SHOW_EXCLUDED_LANGUAGE_TABS` enabled by accident?
