### ISSUE TITLE
Cannot enter more than 50 characters in TranslatedFields if it is CharField

### ISSUE THREAD

**Issue by koztay** [django-parler/django-parler#209]
I cannot enter more than 50 characters in my class based view for my `event_title` field. The error says
`django.db.utils.DataError: value too long for type character varying(50)`
My model is as folows and I already set max_length as 250 characters but no way. The weird thing is if I create the object with less than 50 characters then I can inrease the length of title more than 50 characters. I did not figured out whats happening.
```python
class Event(TranslatableModel):
    """
    Event model
    """
    translations = TranslatedFields(
        event_title=models.CharField(max_length=250, verbose_name=_('aktivite başlığı')),
        slug=models.SlugField(_("event slug"), blank=True),
        description=models.TextField(verbose_name=_('açıklama ve detaylar')),
        any_language=True,
    )
    objects = EventQuerySet.as_manager()

    def __str__(self):
        return self.event_title

    def get_absolute_url(self):
        return reverse("events:event_detail", kwargs={"pk": self.pk, "slug": self.slug})

    class Meta:
        ordering = ('start', 'pk')
```

**Comment by vdboor** [comment]
did you create new database migrations after changing the model? I think your database still has the previous value in it's table definition.

**Comment by koztay** [comment]
I have solved it. This was not because of parler. I am using awesome-slugify and its' default value for max_length is 50. So, when I override it everything has been solved.

**Comment by vdboor** [comment]
thanks for letting me know!
