### ISSUE TITLE
Initial contents for translated fields that require additional processing (e.g. JSONField) are not set correctly. 

### ISSUE THREAD

**Issue by airsource** [django-parler/django-parler#226]
I noticed that the admin interface for translated fields contained incorrectly formatted data when using [JSONField](https://github.com/dmkoch/django-jsonfield) and I did some digging to try to work out why. I've narrowed it down to around line 67 of forms.py when the setdefault is called on the BaseTranslatableModelForm, though I confess I'm not entirely sure how to fix it as my Django internals and Parler internals knowledge is somewhat limited! I've had a go and will submit a pull request with my small change, which appears to work.

**Comment by airsource** [comment]
Please also find attached a Django project demonstrating the issue. To reproduce:

1. Install the packages specified in requirements.txt
1. Create your admin user using createsuperuser and then runserver
1. Go to the admin interface
1. Enter a sample piece of JSON in the TestModel, save. Now go in again and notice that the JSON is formatted correctly.
1. Enter a sample piece of JSON in the TestTranslatedModel, save. Now go in again and notice that the JSON is formatted incorrectly.

[test.zip](https://github.com/django-parler/django-parler/files/2127900/test.zip)

**Comment by vdboor** [comment]
I've merged your PR #227
