### ISSUE TITLE
Error deleting translations

### ISSUE THREAD

**Issue by spexii** [django-parler/django-parler#234]
Hi!

And first of all, thanks for your great translation package for Django.

I faced problems when I'm trying to delete translation in Django Admin. I'm trying to delete translations clicking the red 'x' in the language tab. Clearing the translated field and saving it doesn't delete translation - the row stays in the database table with the empty field. I'm using Django 2.1.2 and the newest version of django-parler, 1.9.2.

There's a different error message when trying to delete a translation from a 'regular' model and when trying to delete a translation from a polymorphic model.

Error when trying to remove finnish translations from a non-polymorphic country object:

```
TypeError at /en/admin/core/country/5a98f0e9-7c88-44f7-9324-2170ee20a523/change/delete-translation/fi/
get_deleted_objects() takes 3 positional arguments but 5 were given
Exception Location: /home/myproject/.local/share/virtualenvs/myproject-Mc46aRDC/lib/python3.6/site-packages/parler/admin.py in delete_translation, line 462
```
And the error when trying to remove swedish translation from a polymorphic model:

```
ValidationError at /en/admin/product/product/514cb374-7f8d-4007-9452-914732df0f42/change/delete-translation/sv/change/
["'514cb374-7f8d-4007-9452-914732df0f42/change/delete-translation/sv' is not a valid UUID."]
Exception Location: /home/myproject/.local/share/virtualenvs/myproject-Mc46aRDC/lib/python3.6/site-packages/django/db/models/fields/__init__.py in to_python, line 2330
```
For the latter error I don't have an idea yet, but the first error is pointing to the admin.py file in parler and I started to check that file. The current admin.py in GitHub has different way using the get_deleted_objects() function:

```
# admin.py in django-parler 1.9.2

deleted_result = get_deleted_objects(qs, qs_opts, request.user, self.admin_site, using)
if django.VERSION >= (1, 8):
    (del2, model_counts, perms2, protected2) = deleted_result
else:
    (del2, perms2, protected2) = deleted_result

# admin.py in GitHub

if django.VERSION >= (2, 1):
    deleted_result = get_deleted_objects(qs, request, self.admin_site)
else:
    deleted_result = get_deleted_objects(qs, qs_opts, request.user, self.admin_site, using)
(del2, model_counts, perms2, protected2) = deleted_result
```
I was wondering, could that new admin.py solve my problem? The django-parler 1.9.2 has been released in February, what is the plan for next release and these changes for example in admin.py? I know I could just get a copy of the admin.py here in GitHub, but I haven't tested yet does it work or does it need some other changed files, too.

And it would also be nice if someone has a clue for my second error :)

**Comment by milkomeda** [comment]
I'm also affected and a new release would be appreciated. Thanks for the great work so far.

**Comment by vdboor** [comment]
A new release is coming up within a day! Sorry it took so long
