### ISSUE TITLE
Release 1.9.3

### ISSUE THREAD

**Issue by chessbr** [django-parler/django-parler#237]
Any plans to release new version? I am currently having issues with 1.9.2 that was fixed after that. Can you bump the project @vdboor any time soon?

**Comment by valberg** [comment]
@vdboor Ping on this! I'm happy to help!

**Comment by xavfernandez** [comment]
I've tried contacting the author by mail and did not get a response.
In the mean time I've created a fork https://github.com/Polyconseil/django-parler-encore and released it.
It includes django-parler's master (11ae4af) and @mireq's fix from https://github.com/django-parler/django-parler/pull/244 (the main motivation for the work, as we'd like to switch to Django 2.2).

**Comment by cyberbudy** [comment]
+1

**Comment by vdboor** [comment]
Hi guys! Sorry this took so long.

I've just reviewed all open PR's and merged those. I'll wait for @jrief to have a final sign-off too and release the project afterwards!

**Comment by vdboor** [comment]
@valberg help is certainly welcome! You can message me at vdboor at edoburu.nl for details!

**Comment by xavfernandez** [comment]
@vdboor if a 2.0 is planned, it might be a good time to drop support for:
- Django 2.0 (end of life [April 2019](https://www.djangoproject.com/weblog/2015/jun/25/roadmap/) )
- Python 3.4 (end of life [March 2019](https://www.djangoproject.com/weblog/2015/jun/25/roadmap/)

I'd also be tempted to drop Django 1.11 & Python 2.7 as this would permit most of the cleanup but I understand this might be more controversial.

**Comment by vdboor** [comment]
Release 2.0 is out! 🎉 

@xavfernandez dropping Django support makes total sense to me. In this case, 2.0 already drops support for 1.7/1.8/1.9/1.10. This also allows it to be a transitional release towards newer Django versions, plus I didn't want to touch an tested code base. This is surely something we could address in a 2.1 release!
