### ISSUE TITLE
ImportError: cannot import name 'pretty_name' from 'django.forms.forms' (/home/shampad/Desktop/more_python/BookShop-stage1/venv/lib/python3.8/site-packages/django/forms/forms.py)

### ISSUE THREAD

**Issue by sompodsign** [django-parler/django-parler#283]
how to fix the error. ? 
ImportError: cannot import name 'pretty_name' from 'django.forms.forms' (/home/shampad/Desktop/more_python/BookShop-stage1/venv/lib/python3.8/site-packages/django/forms/forms.py)

**Comment by openhubdev** [comment]
I got the same issue after installing django-parler....

**Comment by openhubdev** [comment]
when I compare the 'django.forms.forms' @python3.9  w this https://docs.djangoproject.com/en/2.1/_modules/django/forms/forms/, obviously "pretty_name" is missing:
`from django.forms.utils import ErrorDict, ErrorList, **pretty_name**  `
So when I patched that manually to 'python3.9/site-packages/django/forms/forms.py' , it did eliminate the error; HOWEVER I am pretty sure that is not the solution. How to request that to be added t that file?

**Comment by pgsbird** [comment]
Change the from django.forms.forms  To  django.forms.utils

**Comment by RubenVer** [comment]
> Change the from django.forms.forms To django.forms.utils

There is already a file named utils in django.forms directory.
I'm facing the same issue, but can't resolve it by adding pretty_name to django.forms.forms.
If I add pretty_name, then I get other errors:
ImportError: cannot import name 'BoundField' from 'django.forms.forms'

**Comment by habnk** [comment]
> Change the from django.forms.forms To django.forms.utils

it work for me

**Comment by jrief** [comment]
Is this error related to django-parler or a 3rd party library.
django-parler imports `pretty_name` from the correct location, so I don't understand what to report here.
I going to close this issue.

**Comment by ShamsiddinToshmirzaev** [comment]
It 's because of django-parler version
