### ISSUE TITLE
Django Elasticsearch DSL + Parler -> How?

### ISSUE THREAD

**Issue by michalpulpan** [django-parler/django-parler#314]
Hello,

first of all, thank you for very good Django add-on. 
I'm currently in a proccess of connecting [](https://django-elasticsearch-dsl.readthedocs.io/en/latest/#django-elasticsearch-dsl)Django Elasticsearch DSL to models that is derived from `TranslatableModel`. 

Is there any way to actually create `django_elasticsearch_dsl` `Document` object that would use, as it's fields, `django-parler` `TranslatedFields`?
My issue is that each language requires different approach so I need to handle each lang specifically.

For example model looks like this

```Python
# models.py

class Product(TranslatableModel):
  ...
  translations = TranslatedFields(
        title=models.CharField(max_length=200, blank=True, help_text='')
  )
  ...
```

What I currently do is to define function on `Product` such as:
```Python
@property
def cs_title_to_string(self): return self.safe_translation_getter('title', language_code='cs')
```

And later I call it from my `Document` obj.

```Python
# documents.py
@registry.register_document
class ProductDocument(Document):
  'title__cs': fields.TextField(
     attr='cs_title_to_string', # <-- HERE! But it's no where near nice solution...
       fields={
         'raw': fields.KeywordField(),
       }
  )
```

Thanks!

**Comment by jrief** [comment]
please ask these kind of questions in the **Discussions** board.

**Comment by jrief** [comment]
see #315
