### ISSUE TITLE
Creation of the parent, although max length has been exceeded

### ISSUE THREAD

**Issue by MaehMaeh** [django-parler/django-parler#350]
I have the problem that when I create a new object via `Status.objects.create(code=1, name="12345678901")`, I get an error message `django.db.utils.DataError: ERROR: Value too long for type character varying(10)`, but the status object is still created. In my opinion, the status object must not even be created if the max length of `name` is not correct. Do you have the same problem or is there something wrong with my settings?

Model:
```
class Status(TranslatableModel):
    code = models.IntegerField(unique=True)
    translations = TranslatedFields(
        name=models.CharField(max_length=10, blank=True),
    )
```

**Comment by DylannCordel** [comment]
Hi @MaehMaeh 

If you do not want to check data **before** the creation, you should use [atomic transactions](https://docs.djangoproject.com/fr/5.0/topics/db/transactions/) to resolve your problem.

```
from django.db import transaction
with transaction.atomic():
    try:
        Status.objects.create(code=1, name="12345678901")
    except Exception as e:
        ...  # some fallback ?
```

IMHO, this is not a real problem for `django-parler` and this issue should be closed.

**Comment by MaehMaeh** [comment]
Many thanks for the answer.

Hmm, if it's that simple, then I didn't see the wood for the trees. Probably my problem was understanding that it is only one call (Status.objects.create) and that's why I didn't think of working with `transaction.atomic()`.

If this is the solution, the task can be closed.
