### ISSUE TITLE
Optional translation object not created in admin

### ISSUE THREAD

**Issue by martinsvoboda** [django-parler/django-parler#80]
Hello,
if all translation fields are only optional and user do not fulfill values in Django admin, translation object is not created. Is possible to force creation of object?

Example of model:

``` python
class Author(TranslatableModel):
    translations = TranslatedFields(
        name = models.ForeignKey('AuthorName', blank=True, null=True),
        description = models.TextField(blank=True),
        like_count = models.BigIntegerField(default=0),
        quote_count = models.BigIntegerField(default=0),
    )
```

**Comment by vdboor** [comment]
Hi! This seems to be a bug!

Yes, you can create a translation object forcefully.
For example, try something like this (typed here from memory):

`def save_model(self, object):
    super(..).save_model(self, object)
    lang = obj.get_current_language()
    if not object.has_translation(lang):
        object.create_translation(lang)
```

**Comment by martinsvoboda** [comment]
Thank you for workaround, I will try to fix this in django-parler codebase.

**Comment by vdboor** [comment]
The PR is merged in a separate test-me branch. Hence I'll leave this ticket open for now.

**Comment by mdentremont** [comment]
@vdboor Any chance we could get this merged?

**Comment by mdentremont** [comment]
@vdboor: I made these changes directly to `TranslatableModelMixin` and it seems to work very well. All of our ~6k tests continue to pass.

**Comment by vdboor** [comment]
@mdentremont : thanks for the reminder! I've merged the code now in git master.

**Comment by mdentremont** [comment]
@vdboor Awesome!
